 <!-- Header -->
  <div id="header">
    <!-- Logotyp -->
    <h1 id="logo"><a href="/">Sergik<strong>-Blog</strong><span></span></a></h1>
    <hr class="noscreen" />
    <!-- Quick links -->
    <div class="noscreen noprint">
      <p><em>Quick links: <a href="#content">content</a>, <a href="#tabs">navigation</a>, <a href="#search">search</a>.</em></p>
      <hr />
    </div>
    <!-- Search -->
    <!--<div id="search" class="noprint">
      <form action="#" method="get">
        <fieldset>
        <legend>Search</legend>
        <label><span class="noscreen">Find:</span> <span id="search-input-out">
        <input type="text" name="" id="search-input" size="30" />
        </span></label>
        <input type="image" src="design/search_submit.gif" id="search-submit" value="OK" />
        </fieldset>
      </form>
    </div> -->
    <!-- /search -->
  </div>
  <!-- /header -->
  <!-- Main menu (tabs) -->
  <div id="tabs" class="noprint">
    <h3 class="noscreen">Navigation</h3>
    <ul class="box">
      <li id="active"><a href="/">Weblog<span class="tab-l"></span><span class="tab-r"></span></a></li>
      <!-- Active -->
      
    </ul>
    <hr class="noscreen" />
  </div>
  <!-- /tabs -->
  <!-- Page (2 columns) -->
  <div id="page" class="box">
    <div id="page-in" class="box">
     <!-- <div id="strip" class="box noprint">
        <!-- RSS feeds -->
     <!--   <p id="rss"><strong>RSS:</strong> <a href="#">articles</a> / <a href="#">comments</a></p>
        <hr class="noscreen" />
        <!-- Breadcrumbs -->
    
    <!--    <hr class="noscreen" />
      </div>
      <!-- /strip -->
      <!-- Content -->