<?php if (count($this->paginator)): ?>
    <?php foreach ($this->paginator as $post ): ?>
        <?php if ($post['is_active']): ?>
        <div class="article">
        <h2><span><a href="<?php echo $this->url(array('catUrl'=>$post['cat_url'],'postUrl' => $post['url']), 'postView') ?>"><?php echo $this->escape($post['title']); ?></a></span></h2>
        <p class="info noprint"> <span class="date"><?echo $post['date'];?></span>
            <span class="noscreen">,</span> <span class="cat"><a href="<?php  echo $this->url(array('catUrl' => $post['cat_url']), 'catView') ?>"><? echo $post['cat_title']?></a></span>
            <span class="noscreen">,</span> <span class="user"><? echo $post['username'];?></span>
            <span class="noscreen">,</span> <span class="comments"><a href="<?php echo $this->url(array('catUrl'=>$post['cat_url'],'postUrl' => $post['url']), 'postView') ?>"> Comments(<?php echo $this->CommentsCount($post['id']); ?>)</a></span> </p>
        <p><?php echo( $post['full_text']); ?></p>
        <p class="btn-more box noprint"><strong><a href="<?php echo $this->url(array('catUrl'=>$post['cat_url'],'postUrl' => $post['url']), 'postView') ?>"">Continue</a></strong></p>
        <br>
        <h3><span>   
                <?php foreach ($post->getTags() as $tag ):?>
                <a href="<?php  echo $this->url(array('tag' => $tag['name']), 'tagView') ?>"><? echo $tag['name']?></a> &nbsp;
                <?php endforeach;?>
            </span></h3>  
        </div> 
       <?php endif;
          endforeach; 
      endif; ?>
<div class="pagination"><?php echo $this->paginationControl($this->paginator,
                                  'Elastic',
                                  '/partials/my_pagination_control.phtml'); ?></div>