<?php 
echo $this->doctype() ?>
<head>  
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
</head> 
<body id="www-url-cz">
<!-- Main -->
<div id="main" class="box">
    <?php echo $this->partial('header.phtml','front', array(
    'title'=>$this->title,
     )); ?>
      <div id="content"><?php echo $this->layout()->content ?></div>
      <div id="col" class="noprint">
        <div id="col-in">
          <h3><span><a href="#">login</a></span></h3>
          <div id="login">
          <? $auth = Zend_Auth::getInstance();
             if (!$auth->hasIdentity()) {
                  echo $this->SetupLoginForm();
                  echo '<p><a href="'.$this->url(array('registration' => 'registration'), 'reg').'">Registration</a></p>'; 
            }else{
                echo 'You loged in as <b>' . $auth->getIdentity()->username .'</b>';
                echo '<p><a href="'.$this->url(array('logOut' => ''), 'logout').'">Logout</a></p>'; ?>
        <? }?>           
          </div>
          <hr class="noscreen" />
          <h3 ><span>Category</span></h3>
          <ul id="category">
            <?php  $cat = new Admin_Model_Cats();
            $categories = $cat->findAll(); ?>
        <?php foreach ($categories as $category) : ?>
          <li><a href="<?php  echo $this->url(array('catUrl' => $category->cat_url), 'catView') ?>"><?php echo $category->cat_title ?></a></li>
        <?php endforeach ?>
          </ul>
         
        </div>
      </div>
    </div>
  </div>
  <?php echo $this->render('footer.phtml','front'); ?>
</div>
</body>
   
</html>